### ISSUE TITLE
Zombie way appears after removing last node of way

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#154]
When you delete a node from a way with 2 nodes, a way dummy will appear (you can restore the way by dragging it). The dummy represents (from my understanding) a way with no nodes, it remains editable, tags can be modified, but the problem is that all the actions are still those for a normal way, some must be removed: If you „duplicate“ the way it will create 2 ways with 0 members, and if you try to „straighten“ the way it crashes.

**Comment by bryceco** [comment]
Yeah, that's a bug! It should be deleted completely when you delete one of the nodes.

**Comment by bryceco** [comment]
Not sure if this was already fixed, needs review.

**Comment by tordans** [comment]
I think the bug is still there. But personally I don’t think it’s a real problem. Video: https://www.dropbox.com/s/lczhdulu87vdf7s/RPReplay_Final1584211710.MP4?dl=0
Map from video https://www.openstreetmap.org/way/334062938

**Comment by bryceco** [comment]
Oh, I misunderstood what was happening. Thanks for the video!

**Comment by bryceco** [comment]
@tordans The screen capture videos you submit are great. With the new Settings - Advanced Settings - Show Touches option it makes it even more obvious what you’re doing. I added it specifically for screen recording.
