### ISSUE TITLE
One finger zoom gesture doesn't work

### ISSUE THREAD

**Issue by euf** [bryceco/GoMap#652]
Comparing to 3.1.4 from App Store, current 3.4.4 from Testflight has a zoom gesture broken. Tap-tap-swipe doesn't work anymore. I find it a huge regression, since I was used to quick one hand mapping. While pinch to zoom still works, it's much less convenient to use both hands on the go. My device is iPhone 12 mini with iOS 16.0 (20A362).

**Comment by bryceco** [comment]
Fixed in 55ede74265f5c2ee1301383143bead09ea55dc7f

**Comment by euf** [comment]
Hello @bryceco, thanks for the fix! Unfortunately after the update I'm still not able to use tap and drag zoom. 

I can see in your commit that you drastically decreased both time and distance for the gesture recognition. 

https://github.com/bryceco/GoMap/commit/55ede74265f5c2ee1301383143bead09ea55dc7f#diff-94b39875f4640dfd18b314f95695cae759d2072bfa1147d16bd0439289e2dee9R19

In an old App Store version I had approximately 1 of 10 false positive gestures (map began zooming while I didn't inted to). Now I have something like 9 of 10 false negatives: I deliberately try to zoom, but it works only when I tap super fast and precisely at the same spot, which is almost impossible even when I'm standing still, and absolutely never works when I'm on the go.

I believe old values were okay. Decreasing distance definitely did no good, it should be forgiving enough for quick tapping while walking with the device. If you feel that timing was too relaxed, maybe try 0.33 as a compromise between 0.5 and 0.25, what do you think?

**Comment by bryceco** [comment]
Yeah I agree it's probably a little too strict now. I'll loosen it up a bit.

**Comment by bryceco** [comment]
I played around with this a bit. I have problems with RSI so I'm a pretty poor double-tapper, but still the 0.25 time limit doesn't seem to be a problem for me. l pretty consistently hit 0.11-0.15 seconds for the time interval. 

Distance is definitely easier to wander further away, and my second taps are anywhere from 5-50 pixels away. I previously set the maximum distance to 22.0 since 44.0 is the recommended minimum button size per iOS guidelines. 

I'm keeping the 0.25 time but increasing distance to 40.0 pixels. I find an accidental zoom to be more intrusive than an accidental pan so I'd rather err on the false-negative side.

**Comment by bryceco** [comment]
Fixed in b12d70fa75cd9c01a1ccbcef6e418e446babc9d7

**Comment by euf** [comment]
Thanks for the fix! Tried 3.4.6, the gesture works just as expected 👍
