### ISSUE TITLE
Address input for the Philippines is wrong and missing important fields

### ISSUE THREAD

**Issue by TagaSanPedroAko** [bryceco/GoMap#666]
Address input for the Philippines has been updated last March, making it closer to the actual format used, but it's still wrong and missing some important fields.

![3DD051A5-0507-419E-8B2D-F9208CB7D405](https://user-images.githubusercontent.com/27714833/236366662-eb3d4f48-00dd-4fed-840f-c8bfa25902b4.jpeg)

Current order is this. District should come between street and city (present position should be for the province)

- House number (addr:housenumber)
- Street (addr:street)
- City (addr:city)
- Postcode (addr:postcode)
- District (addr:district)

The following fields should be shown for the next app update.

- Unit (addr:unit)
- House number (addr:housenumber)
- Street (addr:street)
- District (addr:district)
- City (addr:city)
- Postcode (addr:postcode)
- Province (addr:province)

**Comment by bryceco** [comment]
> Address input for the Philippines has been updated last March

Where was it updated? I'm pulling it from iD and Philippines is still missing:
https://github.com/openstreetmap/iD/blob/develop/data/address_formats.json

**Comment by TagaSanPedroAko** [comment]
It's from the March or April update, which fixed issues with imagery and also came with the latest NSI that time.

**Comment by bryceco** [comment]
This is what iD shows me when I edit in Manila. What software are you using?

<img width="455" alt="Screenshot 2023-05-05 at 5 01 05 PM" src="https://user-images.githubusercontent.com/279734/236586845-ee432df9-91bd-467a-a9cc-d7c3beb97819.png">

**Comment by TagaSanPedroAko** [comment]
It's Go Map, and the image I provided is a screenshot from the app.

**Comment by bryceco** [comment]
Sorry, I guess you're talking about the addition of District in Go Map!!. That was actually due to a bug, and not an intentional change. Basically it started using the default address format for some other country that was slightly better than the default for Philippines. 

Because I pull the address format information from iD the fix has to occur there, and I've submitted a pull request to add info for Philippines: https://github.com/openstreetmap/iD/pull/9630

**Comment by bryceco** [comment]
This is now fixed upstream so should appear in the next release. Thanks for the report!

**Comment by TagaSanPedroAko** [comment]
I have uninstalled and reinstalled the app, but address format hasn't changed. When in PH, the default address format still appears.
